import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
            <div>
            <lr-config
                ctx-name="my-uploader"
                pubkey="854722e0079fefc6d43b"
                maxLocalFileSizeBytes={10000000}
                imgOnly={true}
                sourceList="local, url, camera, dropbox"
            ></lr-config>
            <lr-file-uploader-regular
                css-src="https://cdn.jsdelivr.net/npm/@uploadcare/blocks@0.30.0/web/lr-file-uploader-regular.min.css"
                ctx-name="my-uploader"
                class="my-config"
            >
            </lr-file-uploader-regular>
            </div>
            <div>
            <lr-config ctx-name="my-uploader" pubkey="f7f8d4e0f5616dba10ef">
                  </lr-config>
                  <lr-file-uploader-minimal       css-src="https://cdn.jsdelivr.net/npm/@uploadcare/blocks@0.30.0/web/lr-file-uploader-minimal.min.css"
                      ctx-name="my-uploader"
                      class="my-config">
            </lr-file-uploader-minimal>
          </div>
      </body>
    </html>
  )
}
